name: Release
on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  issues: write
  contents: write
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install @semantic-release/git @semantic-release/exec --no-save
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: "ProsperoKay"
          GIT_AUTHOR_EMAIL: "prosperokay@gmail.com"
          GIT_COMMITTER_NAME: "ProsperoKay"
          GIT_COMMITTER_EMAIL: "prosperokay@gmail.com"
